# .kodiak.toml
# docs: https://kodiakhq.com/docs/config-reference

version = 1

[approve]
#auto_approve_usernames = ["dependabot"]

[merge]
automerge_label = [" ğŸ¥³ï¸ LGTM", "ğŸ¥³ï¸ LGTM","ğŸ¥³ï¸  LGTM","LGTM"]
blocking_labels = [" ğŸš§ï¸ WIP", "ğŸš§ï¸ WIP","ğŸš§ï¸  WIP","WIP"]
delete_branch_on_merge = true
method = "squash"
optimistic_updates = true
prioritize_ready_to_merge = true
require_automerge_label = true

[merge.automerge_dependencies]
#usernames=["dependabot","dependabot[bot]","dependabot%5Bbot%5D"]
#versions=["minor", "patch"]

[merge.message]
body = "pull_request_body"
body_type = "markdown"
include_pr_number = true
strip_html_comments = true
title = "pull_request_title"

[update]
always = true
ignored_usernames = ["dependabot"]
autoupdate_label = "ğŸ”„ï¸ Conflict"
