name: 'ðŸŽ‰ï¸  Init'

on: workflow_call

jobs:
  init:
    name: 'ðŸ‘·ï¸  Init'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: 'ðŸ™ï¸  Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: 'ðŸ’½ï¸  Node (16)'
        id: node-setup
        uses: actions/setup-node@v2
        with:
          # architecture: 'x64'
          cache-dependency-path: yarn.lock
          cache: 'yarn'
          node-version: '16'

      - name: 'ðŸ“¦ï¸  Dependencies'
        id: dependencies
        run: |
          yarn install --frozen-lockfile --ignore-engines --network-concurrency 1

      # - name: 'ðŸ”ºï¸  Cache (turbo)'
      #   id: cache-turbo
      #   uses: actions/cache@v2
      #   with:
      #     path: .cache-turbo
      #     key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
      #     # order of preference => turbo will re-check
      #     restore-keys: |
      #       turbo-${{ github.job }}-${{ github.ref_name }}-
      #       turbo-${{ github.job }}-
      #       turbo-
