name: 'ğŸ’½ï¸  '

on: workflow_call

jobs:
  init:
    name: 'ğŸ’½ï¸  '
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: 'ğŸ™ï¸  Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: 'ğŸ’½ï¸  Node (16)'
        id: node-setup
        uses: actions/setup-node@v2
        with:
          # architecture: 'x64'
          cache-dependency-path: yarn.lock
          cache: 'yarn'
          node-version: '16'

      - name: 'ğŸ“¦ï¸  Dependencies'
        id: dependencies
        run: |
          yarn install --frozen-lockfile --ignore-engines --network-concurrency 1
